### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by fwarmuth** [philkr/gamehook#11]
Hey,
i try to compile the project.
Compiling dxgi.dll <-> gamehook.dll works fine.

But the problem is that i cant compile the plugins:
plugin/**capture**, works -> no error
plugin/**python**, error: Cannot open include file: 'Python.h': No such file or directory
plugin/**server**, error: Cannot open include file: 'server_http.hpp': No such file or directory

and yes, these files do not exist.
**Where can i find them?**
and yes i have a python env installed. And even in Visual Studio i installed the python stuff.
regards

**Comment by fwarmuth** [comment]
**UPDATE:**
plugin/**capture**, works -> no error
plugin/**python**, works now -> **fix:** manual adding **lib** and **include** directory of python to the "python plugin" project.
plugin/**server**, works now -> cloned https://gitlab.com/eidheim/Simple-WebSocket-Server and https://gitlab.com/eidheim/Simple-Web-Server to the ./plugins/server/external/

**Comment by gianlucamaugeri** [comment]
@fwarmuth which lib and include directory you used?
