### ISSUE TITLE
binary '>>' : no operator defined which takes a left-hand operand of type 'std::istringstream' (or there is no acceptable conversion)

### ISSUE THREAD

**Issue by zch24879** [philkr/gamehook#15]
When I compile the source, my visual studio 2017 report the error "binary '>>' : no operator defined which takes a left-hand operand of type 'std::istringstream' (or there is no acceptable conversion)" Who knows what the problem might be?

**Comment by gianlucamaugeri** [comment]
@zch24879 try to use refactor branch

**Comment by zch24879** [comment]
> @zch24879 try to use refactor branch

Thanks!

**Comment by gianlucamaugeri** [comment]
@zch24879 please tell me if your gamehook.dll is working fine

**Comment by zch24879** [comment]
> @zch24879 please tell me if your gamehook.dll is working fine

No, I compiled successfully and got the gamehook.dll. But when I try to open the game which I want to test, although I can see the Intercept log, the game break and told me"Your Operating System does not support DirectX12". I attend -dx11 to the game and then the report becomes"Fixing DX11 feature level 10.0 is required to run the engine" .The game can work normally without the dxgi.dll and capture.hk, and my computer's system is win10 1909(10.0.18363), GPU is GeForce GTX 1660 SUPER and I have the newest driver from NVIDIA GeForce Experience. My computer should have DirectX12 theoretically. I use "dxdiag" to detect the version of DirectX and it show me I have DirectX 12. So now I'm confused about this situation and try to solve it.

**Comment by gianlucamaugeri** [comment]
> > @zch24879 please tell me if your gamehook.dll is working fine
> 
> No, I compiled successfully and got the gamehook.dll. But when I try to open the game which I want to test, although I can see the Intercept log, the game break and told me"Your Operating System does not support DirectX12". I attend -dx11 to the game and then the report becomes"Fixing DX11 feature level 10.0 is required to run the engine" .The game can work normally without the dxgi.dll and capture.hk, and my computer's system is win10 1909(10.0.18363), GPU is GeForce GTX 1660 SUPER and I have the newest driver from NVIDIA GeForce Experience. My computer should have DirectX12 theoretically. I use "dxdiag" to detect the version of DirectX and it show me I have DirectX 12. So now I'm confused about this situation and try to solve it.

@zch24879 try to compile in Release x64 (send an email to gianluca.maugeri@unimore.it, we can collaborate)
